apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "afzaldemoaks-50a7"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "afzaldemoaks-50a7"
    spec:
      containers:
        - name: "afzaldemoaks-50a7"
          image: "javaapiregis.azurecr.io/afzaldemoaks"
          ports:
          - containerPort: 8080